/**
 * xmlParser.ts
 *
 * Parses wiki_structure.xml generated by the DeepWiki Open agent.
 * Ported from vscode-ext's deepwiki/xmlParser.ts with no logic changes.
 */
import * as fs from 'fs';

export interface DeepWikiPage {
  id: string;
  title: string;
  description?: string;
  importance?: string;
  relevantFiles?: string[];
  parentSection?: string;
  /** Derived from title: spaces → underscores + ".md" */
  fileName: string;
}

export interface DeepWikiSection {
  id: string;
  title: string;
  pages: DeepWikiPage[];
  subsections: DeepWikiSection[];
}

export interface DeepWikiStructure {
  title: string;
  description: string;
  sections: DeepWikiSection[];
  pagesMap: Map<string, DeepWikiPage>; // page-id → page
}

export class DeepWikiXmlParser {
  private static titleToFileName(title: string): string {
    // Mirror DeepWiki generator's filename sanitizer to avoid mismatches
    // and accidental subdirectories from characters like '/' in titles.
    let base = title.trim();

    // Replace path separators explicitly so titles can't create subdirectories.
    base = base.replace(/[\/\\]/g, '_');

    // Replace any run of characters that aren't alphanumerics, dot, underscore,
    // or dash with a single underscore.
    base = base.replace(/[^A-Za-z0-9._-]+/g, '_');

    // Collapse multiple underscores and trim leading/trailing underscores.
    base = base.replace(/_+/g, '_').replace(/^_+|_+$/g, '');

    // Fallback if everything was stripped.
    if (!base) {
      base = 'page';
    }

    return base + '.md';
  }

  static parse(xmlFilePath: string): DeepWikiStructure {
    const xml = fs.readFileSync(xmlFilePath, 'utf-8');

    const structure: DeepWikiStructure = {
      title: this.extractValue(xml, 'title') || 'DeepWiki Documentation',
      description: this.extractValue(xml, 'description') || '',
      sections: [],
      pagesMap: new Map(),
    };

    // Parse the flat <pages> block that appears AFTER </sections>
    const rootPagesMatch = xml.match(/<\/sections>\s*<pages>([\s\S]*?)<\/pages>/);
    if (rootPagesMatch) {
      const pagesSection = rootPagesMatch[1];
      const pageRegex = /<page\s+id="([^"]+)">([\s\S]*?)<\/page>/g;
      let m;
      while ((m = pageRegex.exec(pagesSection)) !== null) {
        const page: DeepWikiPage = {
          id: m[1],
          title: this.extractValue(m[2], 'title') || '',
          description: this.extractValue(m[2], 'description'),
          importance: this.extractValue(m[2], 'importance'),
          parentSection: this.extractValue(m[2], 'parent_section'),
          relevantFiles: this.extractMultipleValues(m[2], 'file_path'),
          fileName: '',
        };
        page.fileName = this.titleToFileName(page.title);
        structure.pagesMap.set(page.id, page);
      }
    }

    const sectionsXml = this.extractSection(xml, 'sections');
    if (sectionsXml) {
      structure.sections = this.parseSections(sectionsXml, structure.pagesMap);
    }

    return structure;
  }

  private static parseSections(
    sectionsXml: string,
    pagesMap: Map<string, DeepWikiPage>,
  ): DeepWikiSection[] {
    const sections: DeepWikiSection[] = [];
    const sectionRegex = /<section\s+id="([^"]+)">([\s\S]*?)<\/section>/g;
    let m;

    while ((m = sectionRegex.exec(sectionsXml)) !== null) {
      const section: DeepWikiSection = {
        id: m[1],
        title: this.extractValue(m[2], 'title') || '',
        pages: [],
        subsections: [],
      };

      const pagesSection = this.extractSection(m[2], 'pages');
      if (pagesSection) {
        const refRegex = /<page_ref>([^<]+)<\/page_ref>/g;
        let ref;
        while ((ref = refRegex.exec(pagesSection)) !== null) {
          const page = pagesMap.get(ref[1]);
          if (page) { section.pages.push(page); }
        }
      }

      const subsectionsXml = this.extractSection(m[2], 'subsections');
      if (subsectionsXml) {
        section.subsections = this.parseSections(subsectionsXml, pagesMap);
      }

      sections.push(section);
    }

    return sections;
  }

  private static extractSection(xml: string, tagName: string): string | null {
    const regex = new RegExp(`<${tagName}[^>]*>([\\s\\S]*?)<\\/${tagName}>`, 'i');
    const m = xml.match(regex);
    return m ? m[1] : null;
  }

  private static extractValue(xml: string, tagName: string): string | undefined {
    const regex = new RegExp(`<${tagName}[^>]*>([^<]*)<\\/${tagName}>`, 'i');
    const m = xml.match(regex);
    return m ? m[1].trim() : undefined;
  }

  private static extractMultipleValues(xml: string, tagName: string): string[] {
    const regex = new RegExp(`<${tagName}[^>]*>([^<]*)<\\/${tagName}>`, 'gi');
    const values: string[] = [];
    let m;
    while ((m = regex.exec(xml)) !== null) {
      values.push(m[1].trim());
    }
    return values;
  }
}
